/**
 * @file lib/email/generateReceiptPdf.ts
 * SERVER-SIDE ONLY.
 *
 * Generates the same Salden payroll receipt PDF as the client-side
 * "Download" button in transaction-history/page.tsx, so the emailed
 * attachment is visually identical to what a user downloads manually.
 *
 * jsPDF runs fine in a Node/serverless environment for text-only PDFs
 * (no canvas/DOM dependency needed for this layout).
 */

import { jsPDF } from 'jspdf';

export interface ReceiptPdfInput {
  ref:            string;
  txHash:         string;
  timestamp:      number;      // unix ms
  recipientCount: number;
  token:          string;
  remark?:        string;
  amount:         string;      // human-readable, e.g. "1,250.00"
  executedBy:     'manual' | 'ai_agent';
}

function fmtDate(ts: number): string {
  return new Date(ts).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });
}

export function generateReceiptPdf(input: ReceiptPdfInput): Buffer {
  const doc = new jsPDF();

  // Brand header — Deep Indigo #4F46E5
  doc.setFontSize(18);
  doc.setTextColor(79, 70, 229);
  doc.text('SALDEN PAYROLL RECEIPT', 20, 24);

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(`Reference: ${input.ref}`,        20, 36);
  doc.text(`Date: ${fmtDate(input.timestamp)}`, 20, 46);
  doc.text(`Transaction: ${input.txHash}`,   20, 56);
  doc.text(`Recipients: ${input.recipientCount}`, 20, 66);
  doc.text(`Token: ${input.token}`,          20, 76);

  let yPos = 86;
  if (input.remark) {
    doc.text(`Remark: ${input.remark}`, 20, yPos);
    yPos += 10;
  }

  const executedByLabel = input.executedBy === 'ai_agent'
    ? 'Executed by: Salden AI Payroll Agent (autonomous)'
    : 'Executed by: Employer (manual)';
  doc.text(executedByLabel, 20, yPos);
  yPos += 14;

  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text(`Total Amount: ${input.amount} ${input.token}`, 20, yPos);

  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by Salden · Arc Testnet', 20, 280);

  const arrayBuffer = doc.output('arraybuffer');
  return Buffer.from(arrayBuffer);
}
